# This workflow file contains a basic layout for creating your docker image, pushing it to GCR, and then deploying it somewhere. 
# To add this to your workflow, make a folder called '.github' on the highest level of the directory (same as README.md) and then a folder called 'workflows' inside of that. Then, move this file into that folder.
# This creates a new image on push to main/master, and names it using github sha. 
# Make sure to properly put in the repository secrets of the SA key and other information accordingly. 

# name: Build and Push Image to GCP
# on:
#   push:
#     branches:
#       - master
# env:
#   IMAGE_NAME: vics-app # your image name
#   PROJECT_ID: ${{ secrets.PROJECT_ID }} # your project id, doesn't need to be a secret per se
#   SERVICE_NAME: vics-website # your service name
#   REGION: us-east4 # your region

# jobs:
#   build-push-gcr:
#     name: Build and Push to GCR
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v2

#       - uses: google-github-actions/setup-gcloud@94337306dda8180d967a56932ceb4ddcf01edae7
#         with:
#           service_account_key: ${{ secrets.GCP_SA_KEY }} # your service account key
#           project_id: ${{ secrets.PROJECT_ID }} # your project id

#       - run: |-
#           gcloud --quiet auth configure-docker

#       - name: Build Docker Image
#         run: |-
#           docker build \
#           --tag "gcr.io/$PROJECT_ID/$IMAGE_NAME:$GITHUB_SHA" \ # this is the image name, you can change it to whatever you want
#           --build-arg "GITHUB_SHA=$GITHUB_SHA" \ 
#           --build-arg "GITHUB_REF=$GITHUB_REF" \
#           .

#       - name: Push Docker Image
#         run: |-
#           docker push "gcr.io/$PROJECT_ID/$IMAGE_NAME:$GITHUB_SHA"

# Below is an example of deploying to cloud run. You can also deploy to GKE, App Engine, etc. Edit accordingly. 

#   deploy-to-cloud-run:
#     name: Deploy to Cloud Run
#     needs: build-push-gcr
#     runs-on: ubuntu-latest
#     steps:
#       - uses: google-github-actions/setup-gcloud@94337306dda8180d967a56932ceb4ddcf01edae7
#         with:
#           service_account_key: ${{ secrets.GCP_SA_KEY }}
#           project_id: ${{ secrets.PROJECT_ID }}
#       - name: Deploy
#         run: |-
#           gcloud run deploy ${{ env.SERVICE_NAME }} --image=gcr.io/${{ secrets.PROJECT_ID }}/${{ env.IMAGE_NAME }}:${{ github.sha }} \
#           --region=${{ env.REGION }} \
#           --platform=managed \
#           --quiet





          
          
          
        
