# name: Publish Package to npmjs
# on:
#   push:
#     branches:
#       - master
# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v3
#       # Setup .npmrc file to publish to npm
#       - uses: actions/setup-node@v3
#         with:
#           node-version: "16.x"
#           registry-url: "https://registry.npmjs.org"
#       - run: npm ci
#       - name: Configure Git identity
#         run: |
#           git config user.name "Charlie Meyer"
#           git config user.email "charlie@charliemeyer.xyz"
#       - run: npm version patch -m "Bump version to %s"
#       - run: npm publish
#         env:
#           NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
name: Publish Package to npmjs and GitHub Packages
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js for npm
        uses: actions/setup-node@v3
        with:
          node-version: "16.x"
          registry-url: "https://registry.npmjs.org"

      - name: Install dependencies
        run: npm ci

      - name: Configure Git identity
        run: |
          git config user.name "Charlie Meyer"
          git config user.email "charlie@charliemeyer.xyz"

      - name: Get current version
        run: echo "::set-output name=current_version::$(node -p "require('./package.json').version")"

      - name: Increment version
        id: increment_version
        run: |
          # Manually increment the version number
          node -p "const semver = require('semver'); const version = require('./package.json').version; console.log(semver.inc(version, 'patch'));"
          echo "::set-output name=updated_version::$(node -p "require('./package.json').version")"

      - name: Publish package to npm
        run: npm publish --tag ${{ steps.increment_version.outputs.updated_version }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Set up Node.js for GitHub Packages
        uses: actions/setup-node@v3
        with:
          node-version: "16.x"
          registry-url: "https://npm.pkg.github.com"

      - name: Publish package to GitHub Packages
        run: npm publish --registry=https://npm.pkg.github.com/
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.increment_version.outputs.updated_version }}
          release_name: Release ${{ steps.increment_version.outputs.updated_version }}
          draft: false
          prerelease: false
